// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwwVoihv8rS8E7A3xUQN3lLtyLz43FUw',
    appId: '1:863593917019:web:d960a5ca78940c975aed7e',
    messagingSenderId: '863593917019',
    projectId: 'flutter-chat-app-429c3',
    authDomain: 'flutter-chat-app-429c3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-429c3.appspot.com',
    measurementId: 'G-C7V8TS52Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsIDQp1wRUSA7WJJvpziUBeVt7ou79thc',
    appId: '1:863593917019:android:fb9b25105bd044ef5aed7e',
    messagingSenderId: '863593917019',
    projectId: 'flutter-chat-app-429c3',
    storageBucket: 'flutter-chat-app-429c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWtxTvH4vV2ZjwWOzwvXbj5ZUBRJcUoGc',
    appId: '1:863593917019:ios:9a1913d6c85118675aed7e',
    messagingSenderId: '863593917019',
    projectId: 'flutter-chat-app-429c3',
    storageBucket: 'flutter-chat-app-429c3.appspot.com',
    iosClientId: '863593917019-pkq19e7gk0e1b3rpfpqeau609so63kqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWtxTvH4vV2ZjwWOzwvXbj5ZUBRJcUoGc',
    appId: '1:863593917019:ios:9a1913d6c85118675aed7e',
    messagingSenderId: '863593917019',
    projectId: 'flutter-chat-app-429c3',
    storageBucket: 'flutter-chat-app-429c3.appspot.com',
    iosClientId: '863593917019-pkq19e7gk0e1b3rpfpqeau609so63kqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
